version: '3'
services:
  consul:
    image: consul:latest
    restart: always
    container_name: consul
    hostname: consul
    network_mode: host
    entrypoint:
      - consul
      - agent
    command:
      - -bootstrap-expect=1
      - -data-dir=/tmp/consuldata
      - -client=0.0.0.0
#      - -bind={{ GetInterfaceIP "eth0" }}
      - -bind={{ GetInterfaceIP "wlp60s0" }}
      - -dev
      - -data-dir=/tmp/consul
      - -dns-port=53
      - -log-level=info
      - -server
      - -ui
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
      - "53:53/udp"
    environment:
      SERVICE_53_NAME: "consul_dns"
      SERVICE_8500_CHECK_HTTP: /ui
      SERVICE_8500_CHECK_INTERVAL: 10s
      SERVICE_8500_CHECK_TIMEOUT: 5s
      SERVICE_8500_NAME: consul
      SERVICE_8500_TAGS: urlprefix-consul*/
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8600_IGNORE: 'yes'
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'yes'
      CONSUL_CLIENT_INTERFACE: 'eth0'
      CONSUL_BIND_INTERFACE: 'eth0'
      CONSUL_HTTP_ADDR: 0.0.0.0

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    network_mode: host
    restart: always
    command: "-cleanup -tags registrator consul://localhost:8500"
    depends_on:
      - consul
    environment:
      SERVICE_TAGS: "infra,consul,registrator"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  fabio:
    container_name: fabio
    hostname: fabio
    image: magiconair/fabio
    network_mode: host
    restart: always
    depends_on:
      - consul
    environment:
      SERVICE_TAGS: "urlprefix-fabio*/"
      SERVICE_9999_NAME: fabio-lb
      SERVICE_9998_CHECK_HTTP: /ui
      SERVICE_9998_CHECK_INTERVAL: 10s
      SERVICE_9998_CHECK_TIMEOUT: 5s
      SERVICE_9998_NAME: fabio-ui
      SERVICE_9998_TAGS: urlprefix-fabio*/
      SERVICE_9999_NAME: fabio-lb
    volumes:
      - /usr/local/docker/consul/config:/etc/fabio
    ports:
      - "9998:9998"
      - "9999:9999"

  vault:
    depends_on:
      - consul
    image: "vault"
    container_name: "vault"
    hostname: "vault"
    network_mode: host
    depends_on:
      - consul
      - fabio
    environment:
      VAULT_ADDR: "http://$HOSTNAME:8200"
      SERVICE_8200_CHECK_HTTP: /ui
      SERVICE_8200_CHECK_INTERVAL: 10s
      SERVICE_8200_CHECK_TIMEOUT: 5s
      SERVICE_8200_NAME: vault
      SERVICE_8200_TAGS: urlprefix-vault*/
    dns:
      - "$HOSTNAME"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/local/docker/consul/config:/config
    entrypoint: vault server -config=/config/vault.hcl


