---
- hosts: consul_servers
  vars:
    repo: "https://github.com/hankerepo/consul.git"
    local_repo_dir: "/tmp/consul"
  remote_user: svc
  tasks:
  - name: ensure apache is at the latest version
    git:
      repo: "{{ repo }}"
      dest: "{{ local_repo_dir }}"
